repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer  # ensures that a file is either empty, or ends with one newline
      - id: check-merge-conflict  # Prevent committing if a merge conflict is unresolved
      - id: check-yaml  # Ensure YAML files are valid
      - id: check-json  # Ensure JSON files are parsable
        args: [ --unsafe ]
      - id: mixed-line-ending  # CRLF is a vulnerability, fix before commit
        args: ['--fix=lf']
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
  - repo: https://github.com/python/black
    rev: '22.6.0'
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
          - --include='\.pyi?$'
        language_version: python3.9
